# FemPrompt Research Pipeline Configuration
# This file defines default settings for the automated literature processing pipeline

pipeline:
  name: "FemPrompt Research Pipeline"
  version: "1.0.0"
  description: "AI-assisted literature research for bias and intersectionality analysis"

# File paths configuration
paths:
  # Input
  zotero_json: "analysis/zotero_vereinfacht.json"

  # Processing directories
  pdf_dir: "analysis/pdfs"
  markdown_dir: "analysis/markdown_papers"
  summaries_dir: "analysis/summaries_final"

  # Output
  vault_dir: "FemPrompt_Vault"

  # Zotero storage (auto-detected if not specified)
  # zotero_storage: "~/Zotero/storage"

# Stage-specific settings
stages:
  # Stage 1: PDF Acquisition
  acquire_pdfs:
    enabled: true
    timeout: 1800  # 30 minutes
    use_zotero_api: false
    # zotero_api_key: "YOUR_KEY_HERE"
    # zotero_library_id: "12345"
    # zotero_library_type: "user"  # or "group"

  # Stage 2: PDF to Markdown Conversion
  convert_pdfs:
    enabled: true
    parallel: false  # Not yet implemented
    max_workers: 4

  # Stage 3: Document Summarization
  summarize:
    enabled: true
    rate_limit_delay: 10  # seconds between API calls
    batch_size: 5
    max_retries: 3
    # Gemini API settings
    temperature: 0.3
    max_tokens: 2048

  # Stage 4: Obsidian Vault Generation
  generate_vault:
    enabled: true
    min_frequency: 2  # Minimum concept frequency for inclusion
    max_concepts: 100  # Maximum concepts to extract
    categories:
      - "Bias Types"
      - "Mitigation Strategies"

  # Stage 5: Quality Testing
  test_quality:
    enabled: true
    target_score: 85  # Minimum acceptable quality score
    fail_on_low_score: false  # Whether to stop pipeline on low score

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_retention_days: 30

# API keys (can also be set as environment variables)
api_keys:
  # Prefer environment variables for security
  # gemini: "${GEMINI_API_KEY}"
  # zotero: "${ZOTERO_API_KEY}"

# Performance settings
performance:
  max_concurrent_downloads: 5
  chunk_size: 8192  # bytes for file downloads
  request_timeout: 30  # seconds

# Error handling
error_handling:
  continue_on_stage_failure: false
  save_checkpoint_on_error: true
  max_retry_attempts: 3
  retry_delay: 5  # seconds

# Notification settings (future feature)
notifications:
  enabled: false
  email: ""
  slack_webhook: ""